apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: web-$CLUSTER_NAME
    cloudProvider: $CLUSTER_NAME
  name: web-$CLUSTER_NAME
spec:
  containers:
  - env:
    - name: NEW_RELIC_BROWSER_APPLICATION_ID
      value: "$NEW_RELIC_BROWSER_APPLICATION_ID"
    - name: NEW_RELIC_BROWSER_LICENSE_KEY
      value: $NEW_RELIC_BROWSER_LICENSE_KEY
    - name: CATALOGUE_HOST
      value: catalogue-$CLUSTER_NAME
    - name: USER_HOST
      value: user-$CLUSTER_NAME
    - name: CART_HOST
      value: cart-$CLUSTER_NAME
    - name: SHIPPING_HOST
      value: shipping-$CLUSTER_NAME
    - name: PAYMENT_HOST
      value: payment-$CLUSTER_NAME
    - name: RATINGS_HOST
      value: ratings-$CLUSTER_NAME
    image: $DOCKERHUB_USER/rs-web:$TAG
    name: web-$CLUSTER_NAME
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cloudProvider: $CLUSTER_NAME
  name: web-$CLUSTER_NAME
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: web-$CLUSTER_NAME
  type: LoadBalancer
status:
  loadBalancer: {}
